#!/bin/bash

jupyter contrib nbextension install --user
jupyter serverextension enable --py githubcommit
jupyter nbextension install --py githubcommit
sudo jupyter nbextension enable --py githubcommit


